### ISSUE TITLE
Sequence Player crash on seq_svc.clear()

### ISSUE THREAD

**Issue by haudren** [fkanehiro/hrpsys-base#836]
I am currently experimenting with choreonoid to check that my generated motions are correct. I play them in choreonoid using the Sequence Player. Those motions are quite long, thus I often call seq_svc.clear() to stop them and start another without having to close choreonoid and restart.

Once in a while, choreonoid crashes, when calling interpolator::pop_back() on a "double free or corruption".
```
#3  0x00007ffff5f9c66e in malloc_printerr (ptr=<optimized out>, 
    str=0x7ffff609ec10 "double free or corruption (!prev)", action=1) at malloc.c:4996
#4  _int_free (av=<optimized out>, p=<optimized out>, have_lock=0) at malloc.c:3840
#5  0x00007fffb44bb231 in interpolator::pop_back() () from /usr/local/lib/SequencePlayer.so
#6  0x00007fffb44bdc8e in seqplay::pop_back() () from /usr/local/lib/SequencePlayer.so
#7  0x00007fffb44bdd48 in seqplay::clear(double) () from /usr/local/lib/SequencePlayer.so
```

Full backtrace here:  https://gist.github.com/haudren/d02a602ca9212d37d6ef

I think that in some cases, we are trying to pop the top element from the interpolator, but due to timing, another instance of pop_back is currently executing (and gets the same pointer to the back element), and thus we try to delete twice the same element.

Any ideas ?

Thank you,
Hervé

**Comment by haudren** [comment]
Note: this issue also affects the version of hrpsys installed on the robot.
