### ISSUE TITLE
QNXのテストが一瞬で終わっている

### ISSUE THREAD

**Issue by k-okada** [fkanehiro/hrpsys-base#868]
from #865 

```
最近Jenkinsのテストが高速だなと思っていた（PR後1分くらいでメールが来る）のですが，
ビルドが走っていないように見えます．

以下のように出ています．

FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or that something is really wrong with github.
```

**Comment by k-okada** [comment]
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2407/console
```

* Configure hrpsys *
-- The C compiler identification is GNU
-- The CXX compiler identification is GNU
-- Check for working C compiler: /usr/qnx650/host/qnx6/x86/usr/bin/qcc
-- Check for working C compiler: /usr/qnx650/host/qnx6/x86/usr/bin/qcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/qnx650/host/qnx6/x86/usr/bin/QCC
-- Check for working CXX compiler: /usr/qnx650/host/qnx6/x86/usr/bin/QCC -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Found OpenRTM-aist 1.1.0 in /opt/jsk
-- Found OpenHRP 3.1.5 in /opt/jsk
-- checking for module 'libxml-2.0'
--   found libxml-2.0, version 2.7.7
-- Found LibXml2: /usr/pkg/lib/libxml2.so
-- Qhull not found
-- Looking for include files CMAKE_HAVE_PTHREAD_H
-- Looking for include files CMAKE_HAVE_PTHREAD_H - found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - not found
-- Check if compiler accepts -pthread
-- Check if compiler accepts -pthread - yes
-- Found Threads: TRUE
CMake Warning at CMakeLists.txt:109 (message):
  Package SDL is not found!


CMake Warning at CMakeLists.txt:113 (message):
  Package OpenGL is not found!


CMake Warning at CMakeLists.txt:117 (message):
  Package GLUT is not found!


-- checking for module 'opencv'
--   package 'opencv' not found
-- checking for module 'opencv-2.3.1'
--   package 'opencv-2.3.1' not found
CMake Warning at CMakeLists.txt:124 (message):
  opencv not found


-- checking for module 'glew'
--   package 'glew' not found
CMake Warning at CMakeLists.txt:129 (message):
  Package GLEW is not found


CMake Warning (dev) at CMakeLists.txt:155 (add_definitions):
  Policy CMP0005 is not set: Preprocessor definition values are now escaped
  automatically.  Run "cmake --help-policy CMP0005" for policy details.  Use
  the cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- compile iob with -DROBOT_IOB_VERSION=2
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/DataLoggerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/StateHolderService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/RobotHardwareService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/WavPlayerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/SequencePlayerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/ForwardKinematicsService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/ExecutionProfileService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/OGMap3DService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/NullService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/EmergencyStopperService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/TimeKeeperService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/Img.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/HRPDataTypes.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/pointcloud.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/ImpedanceControllerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/SoftErrorLimiterService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/CollisionDetectorService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/GraspControllerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/TorqueFilterService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/KalmanFilterService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/VirtualForceSensorService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/StabilizerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/AutoBalancerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/RemoveForceSensorLinkOffsetService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/ServoControllerService.idl exists
Check if /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/idl/TorqueControllerService.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/ClockGenerator.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/CollisionDetector.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/Controller.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/DynamicsSimulator.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/ModelLoader.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/OnlineViewer.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/OpenHRPCommon.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/ViewSimulator.idl exists
Check if /opt/jsk/share/OpenHRP-3.1/idl/OpenHRP/World.idl exists
CMake Warning (dev) at ec/hrpEC/CMakeLists.txt:4 (link_directories):
  This command specifies the relative path

    io

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

-- USE_QPOASES=OFF
CMake Warning (dev) at rtc/RobotHardware/CMakeLists.txt:3 (link_directories):
  This command specifies the relative path

    io

  as a link directory.

  Policy CMP0015 is not set: link_directories() treats paths relative to the
  source dir.  Run "cmake --help-policy CMP0015" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning at rtc/DataLogger/CMakeLists.txt:10 (find_package):
  Could not find module FindPCL.cmake or a configuration file for package
  PCL.

  Adjust CMAKE_MODULE_PATH to find FindPCL.cmake or set PCL_DIR to the
  directory containing a CMake configuration file for PCL.  The file will
  have one of the following names:

    PCLConfig.cmake
    pcl-config.cmake



cc: unknown option: '-dumpversion'
CMake Error at rtc/ServoController/CMakeLists.txt:6 (string):
  string sub-command REGEX, mode MATCHALL needs at least 5 arguments total to
  command.


-- GCC version (NOTFOUND.NOTFOUND) must be at least 4.3 for binary format in ServoSerial.h!
-- Irrlicht not found
-- checking for module 'octomap'
--   package 'octomap' not found
CMake Warning at rtc/CMakeLists.txt:70 (find_package):
  Could not find module FindPCL.cmake or a configuration file for package
  PCL.

  Adjust CMAKE_MODULE_PATH to find FindPCL.cmake or set PCL_DIR to the
  directory containing a CMake configuration file for PCL.  The file will
  have one of the following names:

    PCLConfig.cmake
    pcl-config.cmake



CMake Warning (dev) at CMakeLists.txt:189 (add_subdirectory):
  The source directory

    /tmp/hrpsys-source-867-2015-10-27/src/hrpsys-base-867/test

  does not contain a CMakeLists.txt file.

  CMake does not support this case but it used to work accidentally and is
  being allowed for compatibility.

  Policy CMP0014 is not set: Input directories must have CMakeLists.txt.  Run
  "cmake --help-policy CMP0014" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.
This warning is for project developers.  Use -Wno-dev to suppress it.
-- Configuring incomplete, errors occurred!

=====
$ tar -xvzf /tmp/hrpsys-867-qnx-2015-10-27; cd hrpsys-source-867-2015-10-27/build; #make install
+ grep \*\*\* /tmp/robot-compile-hrpsys-867.log
+ echo done
done
No JDK named ‘null’ found
Setting status of 23441a8b20503974f84cdc769faefac9e1fa579f to SUCCESS with url http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2407/ and message: Merged build finished.
FileNotFoundException means that the credentials Jenkins is using is probably wrong. Or that something is really wrong with github.
java.io.FileNotFoundException: https://api.github.com/repos/fkanehiro/hrpsys-base/statuses/23441a8b20503974f84cdc769faefac9e1fa579f
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1625)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254)
	at org.kohsuke.github.Requester.parse(Requester.java:383)
	at org.kohsuke.github.Requester._to(Requester.java:185)
	at org.kohsuke.github.Requester.to(Requester.java:160)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:702)
	at org.kohsuke.github.GHRepository.createCommitStatus(GHRepository.java:714)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:140)
	at org.jenkinsci.plugins.ghprb.GhprbRepository.createCommitStatus(GhprbRepository.java:122)
	at org.jenkinsci.plugins.ghprb.GhprbBuilds.onCompleted(GhprbBuilds.java:118)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:27)
	at org.jenkinsci.plugins.ghprb.GhprbBuildListener.onCompleted(GhprbBuildListener.java:12)
	at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:201)
	at hudson.model.Run.execute(Run.java:1786)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)

Refer to this link for build results (access rights to CI server needed): 
http://jenkins.jsk.imi.i.u-tokyo.ac.jp:8080/job/hrpsys-qnx/2407/
```

**Comment by k-okada** [comment]
#854 が犯人のように見える

**Comment by k-okada** [comment]
#870 で治るか
